name: Flask-app-ci
on:
 push:
   branches:
      - master
   tags:
      - "v*.*.*"
    
env:
   REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
   REGISTRY_TOKEN: ${{ secrets.REGISTORY_TOKEN }}
   REPO_NAME: ${{secrets.REPO_NAME}}
   
jobs:
   build-push-docker-image:
      runs-on: ubuntu-latest
      steps: 
         - name: checkout code
           uses: actions/checkout@v3
           
         - name: Login to DockerHub
           uses: docker/login-action@v1
           with:
              username: ${{ secrets.REGISTRY_USER }}
              password: ${{ secrets.REGISTORY_TOKEN }}
              
         - name: Get id tag
           id: meta
           run: echo "::set-output name=meta::$(echo ${GITHUB_REF#refs/heads/})-$(git rev-parse --short=7 HEAD)-$(git tag --points-at HEAD)"
         
         - name: Docker build container
           run: docker build --file Dockerfile -t $REGISTRY_USER/$REPO_NAME:${{ steps.meta.outputs.meta }} .
          
         - name: Docker push container
           run: docker push $REGISTRY_USER/$REPO_NAME:${{ steps.meta.outputs.meta }}
